---
# This playbook deploys the whole application stack in this site.

- name: apply common configuration to all nodes
  hosts: all:!localhost
  remote_user: '{{ remote_user }}'
  become: yes
  become_method: sudo
  vars_files:
    - "vars/{{ deploy_method }}.yml"
    - "vars/resources.yml"
  roles:
    - { role: common, tags: common }
    - { role: hadoop-common, tags: hadoop-common }
    - { role: hive, tags: hive }
    - { role: spark, tags: spark }
#    - maven
#    - hive-testbench
    - { role: presto, tags: presto }
