---
# This playbook installs Apache Maven

- file:
    path: /hadoop/maven
    state: directory
    mode: 0755

- name: Install protobuf bindings
  yum: name=protobuf-c.x86_64 state=present
  tags: maven

- unarchive:
    src: "{{ tarball_dest_path }}/{{ maven_binary_name }}"
    dest: /hadoop/maven
    remote_src: True
    extra_opts: "--strip-components=1"
    #creates: /hadoop/maven/LICENSE.txt

