---
# This playbook installs Presto

- file:
    path: /hadoop/presto/prestoadmin
    state: directory
    mode: 0755

- unarchive:
    src: "{{ tarball_dest_path }}{{ prestoadmin_binary_name }}"
    dest: /hadoop/presto/prestoadmin
    remote_src: True
    extra_opts: "--strip-components=1"
    creates: /hadoop/presto/README.txt

- file:
    path: /hadoop/presto/etc/catalog
    state: directory
    mode: 0755

- file:
    path: /hadoop/presto/data
    state: directory
    mode: 0755
 
- unarchive:
    src: "{{ tarball_dest_path }}{{ presto_binary_name }}"
    dest: /hadoop/presto
    remote_src: True
    extra_opts: "--strip-components=1"
    creates: /hadoop/presto/README.txt

- copy:
    src: "{{ tarball_dest_path }}/{{ presto_cli_name }}"
    dest: /hadoop/presto/presto
    mode: 0700

- name: Configure Presto node properties
  template: src=node.properties.j2 dest=/hadoop/presto/etc/node.properties
  notify: Restart Presto
  tags: presto

- name: Configure Presto jvm properties
  template: src=jvm.config.j2 dest=/hadoop/presto/etc/jvm.config
  notify: Restart Presto
  tags: presto 

- name: Configure Presto config properties
  template: src=config.properties.j2 dest=/hadoop/presto/etc/config.properties
  changed_when: true
  notify: Restart Presto
  tags: presto 

- name: Configure Presto hive properties
  template: src=hive.properties.j2 dest=/hadoop/presto/etc/catalog/hive.properties
  notify: Restart Presto
  tags: presto 
